name: inference
version: SRD_on_SAM
phase: test
samshadow_ckpt_path: ./experiments_lightning/tune_sam+diffusion/image_ISTD_lora_mseloss_1e-1contGradnoPenumbra_fromISTD+_scheduler_cycle8e-5_version_24.6/epoch=499.ckpt
save_result_path: ./experiments_lightning/inference/SRD_on_SAM/results
resume: false
resume_path: ./
h_hat: false
patch_tricky: false
scheduler: true

datasets:
  train:
    name: SRD_sam_train
    mode: HR
    dataroot: ./dataset/ISTD_adjusted_C/train
    gt_mask_dir: ./experiments_lightning/tune_sam/ISTD_lora_mseloss_1e-1contGradnoPenumbra_version_23/99_to_train_diffusion/check_mask
#    gt_mask_dir: ./dataset/ISTD_adjusted_C/train/train_B
    batch_size: 4
    val_data_len: 4
    num_workers: 8
    use_shuffle: true
  test:
    name: SRD_sam_val
    mode: LRHR
    dataroot: ./dataset/SRD_DHAN_mask_old/test
    gt_mask_dir: /home/xinrui/hdd1/xinrui/ShadowDiffusion/experiments_lightning/orig_sam/sam_mask_with_bbox/test_old/binary_mask
#    gt_mask_dir: ./dataset/ISTD_adjusted_C/test/test_B
    data_len: -1
    batch_size: 1

model:
  which_model_G: sr3
  unet:
    in_channel: 7
    out_channel: 3
    inner_channel: 64
    norm_groups: 16
    channel_multiplier:
      - 1
      - 2
      - 4
      - 8
    attn_res:
      - 16
    res_blocks: 2
    dropout: 0
  beta_schedule:
    train:
      schedule: linear
      n_timestep: 1000
      linear_start: 1e-4
      linear_end: 0.02
    val:
      schedule: linear
      n_timestep: 1000
      linear_start: 1e-4
      linear_end: 0.02
  diffusion:
    image_size: 512
    channels: 3
    conditional: true

#sam:
#  input_size: 1024
#  loss: iou

train:
  gpu_ids: [0,1]
  accumulate_grad_batches: 2
  max_epochs: 500
  every_n_epochs: 100
  optimizer:
    lr: 1e-4

test:
  gpu_ids: [3]

warmup_epochs: 10

ckpt_path:
  'lora_sam': /home/xinrui/hdd1/xinrui/ShadowDiffusion/experiments_lightning/tune_sam/ISTD_lora_mseloss_1e-1contGradnoPenumbra_version_23/epoch=99.ckpt
  'ddpm':  /home/xinrui/hdd1/xinrui/ShadowDiffusion/experiments/official_test/checkpoint/SRD_dataset/I2130000_E12080 # two ckpts share same name
#  'ddpm': /home/xinrui/hdd1/xinrui/ShadowDiffusion/experiments/official_test/checkpoint/ISTD_plus_dataset/I1710000_E14251
  'SAM':  "/home/xinrui/hdd1/xinrui/ShadowDiffusion/experiments/official_test/SAM_ckpt/sam_vit_h_4b8939.pth"

bbox_path: "./dataset/SRD_DHAN_mask_old/train/bounding_boxes_DHAN.yaml"
test_bbox_path: "./dataset/SRD_DHAN_mask_old/test/bounding_boxes_DHAN.yaml"
# test_bbox_path: "./dataset/SRD_DHAN_mask_old/test/bounding_boxes_DHAN.yaml"
model_type: "vit_h"
sam_rank: 8